### ISSUE TITLE
后端开发工程师实习生招吗？

### ISSUE THREAD

**Issue by GainSury** [strikingly/hiring#1]
[简历地址](https://github.com/GainSury/resume/blob/master/%E5%B9%B2%E5%AE%87%E8%88%AA.pdf)

**Comment by danielglh** [comment]
@GainSury 招的，抱歉我们基本不看这里的 issue 所以拖了挺久，我让 HR 同事跟你联系一下。

**Comment by GainSury** [comment]
@danielglh 好的。

**Comment by GainSury** [comment]
达峰老师您好，没有回复的是不是就是不合格？

2017-04-15 22:41 GMT+08:00 Dafeng <notifications@github.com>:

**Comment by GainSury** [comment]
@dfguo  达峰老师您好，没有回复的是不是就是不合格？
